### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by diplopito** [loopthy/sencha-wysiwyg-editor#1]
Hi, very impressive work, congratulations! 

Could you please add the installation steps to the readme file? Apparently it uses node modules, but could it be integrated with 7.0 GPL?

Thanks!

**Comment by nilzao** [comment]
Hi, check my fork, the app runs, but the code editor is not working.

**Comment by nilzao** [comment]
> Hi, very impressive work, congratulations!
> 
> Could you please add the installation steps to the readme file? Apparently it uses node modules, but could it be integrated with 7.0 GPL?
> 
> Thanks!

nodejs and npm in your o.s. path, then run inside project folder:

`    npm start
`
linux fail with npm max user watches thing, that will fix...

`    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
`

**Comment by diplopito** [comment]
Thanks for your reply @nilzao. I have issues installing node in Ubuntu. On Windows, this is the error log:

In Terminal:
```terminal
> wysiwyg@0.0.1 start F:\xampp\htdocs\xtest\architect
> cross-env-shell npm run dev

'cross-env-shell' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wysiwyg@0.0.1 start: `cross-env-shell npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wysiwyg@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2020-08-18T11_44_50_579Z-debug.log
```
And the error log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'B:\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wysiwyg@0.0.1~prestart: wysiwyg@0.0.1
6 info lifecycle wysiwyg@0.0.1~start: wysiwyg@0.0.1
7 verbose lifecycle wysiwyg@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle wysiwyg@0.0.1~start: PATH: C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\xampp\htdocs\xtest\architect\node_modules\.bin;;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps;F:\xampp\php;\;C:\Users\Daniel\AppData\Roaming\npm;;F:\php-sdk;F:\php-dev;B:\visualstudio2019\VC\bin;C:\Users\Daniel\.dotnet\tools;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle wysiwyg@0.0.1~start: CWD: F:\xampp\htdocs\xtest\architect
10 silly lifecycle wysiwyg@0.0.1~start: Args: [ '/d /s /c', 'cross-env-shell npm run dev' ]
11 silly lifecycle wysiwyg@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle wysiwyg@0.0.1~start: Failed to exec start script
13 verbose stack Error: wysiwyg@0.0.1 start: `cross-env-shell npm run dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid wysiwyg@0.0.1
15 verbose cwd F:\xampp\htdocs\xtest\architect
16 verbose Windows_NT 10.0.19041
17 verbose argv "B:\\nodejs\\node.exe" "C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error wysiwyg@0.0.1 start: `cross-env-shell npm run dev`
22 error Exit status 1
23 error Failed at the wysiwyg@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Any chance to make it work with Ext GPL or the local library?

**Comment by nilzao** [comment]
Try npm install, before running npm start

**Comment by diplopito** [comment]
Thanks for the tip. Not looking better:

```terminal
npm ERR! code EINTEGRITY
npm ERR! sha1-JRyCR5+mo0HAYdd3qgYEttpNynM= integrity checksum failed when using sha1: wanted sha1-JRyCR5+mo0HAYdd3qgYEttpNynM= but got sha512-eiijDW8LjmqMbIxQfIMlw4WkrkqL0l4IvvI8KcwVqKDYV3M7zaMq2/tDWUSaaWNN0jxSFVQYsyMcBpdmmSznbw== sha1-1SAA/ACtUhUHBku/CTB2ud6WqO4=. (21219 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha1-MSGUUyxcSyBr/uKOoIAP3rFmR1w= integrity checksum failed when using sha1: wanted sha1-MSGUUyxcSyBr/uKOoIAP3rFmR1w= but got sha512-3LYasCT3QDSX6ZgbwTU8lJMrG1rhq+C/pVJG/rqqJVh4pHMPP9QG4eQZNV7wIT+07eGTDBmBvP+gPRC0QlHi5w== sha1-zDuBYIXcfzp9QAcIRqmZovAS1Yg=. (47146 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha1-o+SZq0q6i8MPY11vlcAcN9iZpI0= integrity checksum failed when using sha1: wanted sha1-o+SZq0q6i8MPY11vlcAcN9iZpI0= but got sha512-8ngV16P/UKDgnT1/kQzhMTaI6qD3F5DX1n5P0ckjCfnolydXplD98cMwk/8ciF4rQ2v1adEycKLCwuo3zlM0Cg== sha1-Y7d0pK8o8+HhXMX9fne8l7OK3QM=. (52158 bytes)
npm WARN tarball tarball data for @sencha/ext-modern-theme-neptune@7.2.0 (sha1-Ytk2fpMPaXUi4xx1u89WqXYBLz8=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sencha/ext-font-awesome@7.2.0 (sha1-N6fD91KJzbceNdzB9RHXp93eknY=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha1-ylQyM7UGXBBXz5MVJz27yMloomM= integrity checksum failed when using sha1: wanted sha1-ylQyM7UGXBBXz5MVJz27yMloomM= but got sha512-Kao+/g/eUD3pT9Nafvb0I6+gBGqF/NKgXjDM+R5J8kMzYSnYXOgA+6h0fjDzUijaYj4d6wIea32i4yyRmj85vA== sha1-PlfbfOqIjAXhzpfTtbP6vD/5ijk=. (35761 bytes)
npm WARN tarball tarball data for @sencha/ext-core@7.2.0 (sha1-G0fgsGEg8OPStjfeJSQ0zZzVrXA=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha1-v31VlmdehmpbI1/63ELCCc566hg= integrity checksum failed when using sha1: wanted sha1-v31VlmdehmpbI1/63ELCCc566hg= but got sha512-hl3EITFfVh5j4DK2adpzRcoRhUajpvtR/07fM93PSwMS2w3meakgfzDAFabDKLOnY5DKvIGY6T/SjxB+FnIj2Q== sha1-P2y3wUd53Te4+Jn/0ihZbY2eT4g=. (81360 bytes)
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\has-values-e7c22247\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\has-values-e7c22247\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\has-values-e7c22247\LICENSE'
npm WARN tarball tarball data for @sencha/ext-modern-theme-material@7.2.0 (sha1-AL5dwjNEcsLPqbVLTuxfGtDj67c=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\has-values-e7c22247\index.js'
npm WARN tarball tarball data for @sencha/ext-modern@7.2.0 (sha1-UixM8Tcv+NBxVgRk7q4vo5SGZA0=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-font-ext-c6c8c0bc\sass\etc\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\renderkid-2e671906\lib\layout\block\blockPrependor\_BlockPrependor.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\uri-js-dc0b5d84\dist\es5\uri.all.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\upath-3d078272\build\code\upath.js'
npm WARN tarball tarball data for @sencha/ext-modern-theme-neptune@7.2.0 (sha1-Ytk2fpMPaXUi4xx1u89WqXYBLz8=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\renderkid-2e671906\lib\layout\block\blockPrependor\Default.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\uri-js-dc0b5d84\dist\es5\uri.all.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\animation.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\ellipsis.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\ext-hyphens.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-modern-8188858f\.sencha\test\Ext.cmd.api.adapter.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\margin.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-modern-8188858f\.sencha\test\jasmine.js'
npm WARN tar ENOENT: no such file or directory, lstat 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\renderkid-2e671906\lib\layout\block'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\web\FetchCompileWasmTemplatePlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\no-select.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\FlagDependencyExportsPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins\padding.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\package.json'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\sass\etc\mixins.scss'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\FlagDependencyUsagePlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\activate.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\optimize\FlagIncludedChunksPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\license.txt'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\license-include.txt'
npm WARN tarball tarball data for @sencha/ext-font-awesome@7.2.0 (sha1-N6fD91KJzbceNdzB9RHXp93eknY=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sencha/ext-core@7.2.0 (sha1-G0fgsGEg8OPStjfeJSQ0zZzVrXA=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\FlagInitialModulesAsUsedPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\formatLocation.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\@sencha\ext-core-84c06361\build.xml'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\FunctionModulePlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\FunctionModuleTemplatePlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\Generator.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\getFunctionExpression.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\buildin\global.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\GraphHelpers.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\buildin\harmony-module.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyAcceptDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyAcceptImportDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyCompatibilityDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyDetectionParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyExportDependencyParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyExportExpressionDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyExportHeaderDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyExportImportedSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyExportSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyImportDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyImportDependencyParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyImportSideEffectDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyImportSpecifierDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyInitDependency.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\HarmonyLinkingError.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyModulesPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\dependencies\HarmonyTopLevelThisParserPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\HashedModuleIdsPlugin.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\webpack-299872db\lib\HotModuleReplacement.runtime.js'
npm WARN tarball tarball data for @sencha/ext-modern-theme-material@7.2.0 (sha1-AL5dwjNEcsLPqbVLTuxfGtDj67c=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @sencha/ext-modern@7.2.0 (sha1-UixM8Tcv+NBxVgRk7q4vo5SGZA0=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\_limit.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\_limitItems.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\_limitLength.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\_limitProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\renderkid-2e671906\test\renderKid\styles\StyleSheet.coffee'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\allOf.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\renderkid-2e671906\test\tools.coffee'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\anyOf.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\comment.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\const.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\contains.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\custom.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\dependencies.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\enum.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\format.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\if.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\index.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\items.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\multipleOf.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\not.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\oneOf.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\pattern.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\properties.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\propertyNames.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\README.md'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\ref.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\required.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\uniqueItems.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\dotjs\validate.js'
npm WARN tar ENOENT: no such file or directory, open 'F:\xampp\htdocs\xtest\architect\node_modules\.staging\ajv-2b373602\lib\keyword.js'
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sencha/cmd@7.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'architect'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2020-08-18T18_17_30_546Z-debug.log
```

**Comment by nilzao** [comment]
if you want to use the extjs gpl version, use my fork, the extjs gpl version is 7.0.0 only, not 7.2.0

and, to use the gpl version, you need to register at sencha to get access to npm repository, then configure your npm to use that repository (sencha send an email with instructions).

register there:

https://www.sencha.com/legal/GPL/

I don't know why they just don't publish it somewhere public available, and easy to install.

**Comment by diplopito** [comment]
Totally agree with you. I have GPL 7.0 and a Sencha account. I will give it another try. Thanks again!
